#!/bin/sh
# Safe update for a machine that plays games.
#
# Several tracked files are rewritten by simply RUNNING the engine — the tuner
# rewrites data/learned_values.txt, --learn rewrites tmp_learn_game.pgn, matches
# append to matches/*.pgn. Any of them will abort a git pull, which has now
# blocked this repo on the phone four separate times.
#
# Those files are all disposable: the canonical brain lives in Supabase and the
# pgns are logs. So discard local changes to THOSE paths only. Anything else
# modified locally still blocks the pull rather than being silently thrown away
# — if you edited source, you get told, you do not lose it.
set -e
cd "$(dirname "$0")/.."

DISPOSABLE="data/learned_values.txt tmp_learn_game.pgn matches"

for p in $DISPOSABLE; do
    if ! git diff --quiet -- "$p" 2>/dev/null; then
        echo "discarding local changes to $p (regenerated by play)"
        git checkout -- "$p" 2>/dev/null || true
    fi
done

# Anything still dirty is real work; stop rather than clobber it.
LEFT=$(git status --porcelain --untracked-files=no | awk '{print $2}')
if [ -n "$LEFT" ]; then
    echo "NOT pulling — these are modified and are not disposable:"
    echo "$LEFT" | sed 's/^/  /'
    echo "commit or discard them yourself, then rerun."
    exit 1
fi

git pull
make clean && make
./chess test | tail -1
[ -f strategy_weights.txt ] || cp data/strategy_weights_nudged.txt strategy_weights.txt
echo "up to date at $(git log --oneline -1)"
